name: Test and build dyn-wall-rs for Linux and Windows

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Cache Deps
      uses: actions/cache@v2.0.0
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose

  release-linux:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Deps
        uses: actions/cache@v2.0.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target

          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
      - name: Build
        run: cargo build --release
        
      - name: Make directory for assets
        run: mkdir assets
        
      - name: Copy binary over
        run: cp target/release/dyn-wall-rs .
        
      - name: Pack into tarball
        run: tar -czvf dyn-wall-rs-linux.tar.gz dyn-wall-rs
        
      - name: Find sha265sum
        run: sha256sum dyn-wall-rs-linux.tar.gz > assets/dyn-wall-rs-linux.sha256
        
      - name: Move tarball to assets dir
        run: mv dyn-wall-rs-linux.tar.gz assets/
        
      - name: Send tarball and sha256 back
        uses: actions/upload-artifact@v1
        with:
          name: assets-linux
          path: assets/

  release-windows:
    needs: test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Deps
        uses: actions/cache@v2.0.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target

          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release
        
      - name: Make directory for assets
        run: mkdir assets
        
      - name: Copy .exe over
        run: Copy-Item -Path target\release\dyn-wall-rs.exe
        
      - name: zip .exe
        run: tar.exe -a -cf dyn-wall-rs-windows.zip dyn-wall-rs.exe

      - name: Find sha265sum
        run: Get-FileHash dyn-wall-rs-windows.zip -Algorithm SHA256 | Format-List > assets\dyn-wall-rs-windows.sha256
        
      - name: Move zip to assets dir
        run: Move-Item -Path dyn-wall-rs-windows.zip -Destination assets\
        
      - name: Send zip back
        uses: actions/upload-artifact@v1
        with:
          name: assets-windows
          path: assets\
